name: fire_crud
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.15.1
  cloud_firestore: ^4.14.0
  flutter_modular: ^6.3.2
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  mocktail: ^1.0.2
  mobx_codegen: ^2.6.0+1
  build_runner: ^2.4.8
  # flutter packages pub run build_runner build

flutter:
  uses-material-design: true
